### ISSUE TITLE
Comparative experiment

### ISSUE THREAD

**Issue by llooFlashooll** [Aurore54F/JStap#2]
Hi, Professor. I saw your four repositories of `Cujo`, `Zozzle`, `JaSt `and this `JStap`. You really make a good implementation. I want to run some comparative experiments. Do these four repos have the same dataset files construction? JStap has a demo.pdf for launching. I'm wondering whether the others have the same dataset(Good/Bad, train/valid/test) setup to launch?

**Comment by llooFlashooll** [comment]
Through my test, set a valid dataset path then I can launch. Thanks!

**Comment by Aurore54F** [comment]
Hi! Thank you for reaching out.
Could you solve your issue? You can definitely train all detectors on the datasets I shipped with JStap.

**Comment by llooFlashooll** [comment]
Yes! I succeed. Thanks for your timely reply!
But there's a tiny problem with the [Rieck et al. with Cujo](https://www.sec.cs.tu-bs.de/pubs/2010-acsac.pdf) repo. I raise an issue on that repo: https://github.com/Aurore54F/lexical-jsdetector/issues/1. Mainly the error with Jassi.

**Comment by Aurore54F** [comment]
Sure no problem :)
Alright let's discuss that in the other repo then.
