### ISSUE TITLE
Sharing global variable features2int_dict between processes

### ISSUE THREAD

**Issue by JordanGarzon** [Aurore54F/JStap#3]
Hi,

On static_analysis.py, we have `p = Process(target=worker_get_features_vector, args=(my_queue, out_queue, except_queue))`

There you are running worker_get_features_vector that uses inside it features2int_dict. 

This variable is initialized at the beginning of the program ( where we run classifier.py) but it comes back to None when you create a separate process... And then the classifier is not working

Maybe on a specific python version sharing this global variables across processes is possible?

**Comment by Aurore54F** [comment]
Hi Jordan, thanks for reaching out!
I tried running JStap with python 3.7.4 and did not encounter any issues. Which python version are you using? And which exact error message did you get?

Could you try running JStap based on the indications from the file [demo.pdf](https://github.com/Aurore54F/JStap/blob/master/demo.pdf), so on the samples provided and with the scripts provided (you can test with the analysis level `ast` and features `ngrams` as given in the document as an example). I'm trying to rule out the possibility that the issue could come from the samples you used or the way you invoked the functions.

**Comment by JordanGarzon** [comment]
When I am importing your functions from another Python script, it is working well, so I stay like this :) 

Thanks for your answer
