### ISSUE TITLE
Question about the cross-files invocation

### ISSUE THREAD

**Issue by samhsu-dev** [Aurore54F/JStap#4]
Dear developers of JSTAP, 

I notice that jstap accepts multiple JS files as inputs, so I was wondering whether the jstap is able to construct the control flow and dataflow following some functions like module.exports and requires("...") in the NodeJS.

Many thanks

**Comment by Aurore54F** [comment]
Hi Yichao,

So sorry for the late reply. No, JStap does not handle multiple files so far.
When you give several files as input, they are handled separately. This is equivalent to calling JStap on each file individually.

Note: if you are interested specifically in control and data flow analysis (and not the malicious JS part), you can find a refined version of our static analysis [here](https://github.com/Aurore54F/static-pdg-js). This was evaluated on [browser extensions](https://github.com/Aurore54F/DoubleX) :)

**Comment by samhsu-dev** [comment]
> Hi Yichao,
> 
> So sorry for the late reply. No, JStap does not handle multiple files so far. When you give several files as input, they are handled separately. This is equivalent to calling JStap on each file individually.
> 
> Note: if you are interested specifically in control and data flow analysis (and not the malicious JS part), you can find a refined version of our static analysis [here](https://github.com/Aurore54F/static-pdg-js). This was evaluated on [browser extensions](https://github.com/Aurore54F/DoubleX) :)

Hi Aurore54F, 

Thank you a lot for your answer. That is helpful.

Many thanks
